import { cameraScanner } from '../infrastructure/scanner/CameraScanner';
import { logger } from '../shared/utils/logger';
import fs from 'fs';
import path from 'path';

// Ruta al archivo de MediaMTX (ajusta según tu instalación)
const CONFIG_PATH = path.join(__dirname, '../../../mediamtx.yml');

/**
 * Actualiza la configuración de MediaMTX con la IP actual de la cámara
 */
export async function updateMediaMTXConfig(): Promise<void> {
  try {
    logger.info('🔄 Actualizando configuración de MediaMTX...');

    // Obtener IP de la cámara
    const cameraIP = await cameraScanner.getCameraIP();

    if (!cameraIP) {
      logger.warn('⚠️ No se encontró cámara, no se actualiza config');
      return;
    }

    logger.info(`📹 Cámara detectada en: ${cameraIP}`);

    // Verificar que existe el archivo de config
    if (!fs.existsSync(CONFIG_PATH)) {
      logger.warn(`⚠️ No existe ${CONFIG_PATH}, creando configuración básica...`);
      createBasicConfig(cameraIP);
      return;
    }

    // Leer y actualizar config existente
    updateExistingConfig(cameraIP);

  } catch (error: any) {
    logger.error('❌ Error actualizando MediaMTX:', error.message);
  }
}

/**
 * Crea configuración básica de MediaMTX
 */
function createBasicConfig(cameraIP: string): void {
  const basicConfig = `# MediaMTX Configuration
# Auto-generated by Red Ciudadana

rtspAddress: :8554
rtpAddress: :8000
rtcpAddress: :8001

paths:
  camara1:
    source: rtsp://${cameraIP}/stream
    rtspTransport: tcp
    sourceOnDemand: true
`;

  try {
    fs.writeFileSync(CONFIG_PATH, basicConfig);
    logger.info(`✅ Configuración creada con IP: ${cameraIP}`);
  } catch (error: any) {
    logger.error('❌ Error creando config:', error.message);
  }
}

/**
 * Actualiza configuración existente
 */
function updateExistingConfig(cameraIP: string): void {
  try {
    let config = fs.readFileSync(CONFIG_PATH, 'utf8');

    const newSource = `rtsp://${cameraIP}/stream`;

    // Buscar y reemplazar source existente
    const sourceRegex = /source:\s*rtsp:\/\/[\d.:]+\/stream/;

    if (sourceRegex.test(config)) {
      // Reemplazar source existente
      config = config.replace(sourceRegex, `source: ${newSource}`);
    } else {
      // Buscar sección paths y agregar camara1 si no existe
      if (!config.includes('camara1:')) {
        // Agregar después de "paths:"
        config = config.replace(
          /paths:\s*\n/,
          `paths:\n  camara1:\n    source: ${newSource}\n    rtspTransport: tcp\n`
        );
      } else {
        // Agregar source dentro de camara1
        config = config.replace(
          /(camara1:\s*\n)/,
          `$1    source: ${newSource}\n`
        );
      }
    }

    fs.writeFileSync(CONFIG_PATH, config);
    logger.info(`✅ MediaMTX actualizado con IP: ${cameraIP}`);

  } catch (error: any) {
    logger.error('❌ Error actualizando config:', error.message);
  }
}

/**
 * Inicia el monitor de cámara
 */
export function startCameraMonitor(): void {
  logger.info('🎥 Iniciando monitor de cámara...');

  // Primera ejecución después de 3 segundos (para que todo cargue)
  setTimeout(() => {
    updateMediaMTXConfig();
  }, 3000);

  // Ejecutar cada 5 minutos
  setInterval(() => {
    updateMediaMTXConfig();
  }, 5 * 60 * 1000);

  logger.info('⏱️ Monitor configurado: escaneo cada 5 minutos');
}